name-template: v$RESOLVED_VERSION
tag-template: v$RESOLVED_VERSION
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
sort-direction: ascending

categories:
  - title: Breaking changes
    labels:
      - breaking-change
  - title: New features
    labels:
      - new-feature
  - title: Bug fixes
    labels:
      - bugfix
  - title: Enhancements
    labels:
      - enhancement
  - title: Maintenance
    labels:
      - ci
      - dev-environment
  - title: Documentation
    labels:
      - documentation
  - title: Dependency updates
    labels:
      - dependencies

version-resolver:
  major:
    labels:
      - major
      - breaking-change
  minor:
    labels:
      - minor
      - new-feature
  patch:
    labels:
      - bugfix
      - ci
      - dependencies
      - documentation
      - enhancement
  default: patch

template: |
  Thank you for using the KNMI integration! If you find it helpful, please consider starring the repository. ⭐️

  ## What's Changed

  $CHANGES
