name: Bug Report
description: Create a report to help us improve the integration
labels: [bug]
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Did you read the instructions?
      description: Please read the instructions carefully, thank you.
      options:
        - label: I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.
          required: true

  - type: textarea
    validations:
      required: true
    attributes:
      label: The problem
      description: >-
        Describe the issue you are experiencing here to communicate to the
        maintainers. Tell us what you were trying to do and what happened.

        Provide a clear and concise description of what the problem is. What did you expect to happen?

  - type: markdown
    attributes:
      value: |
        ## Environment

  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: What version of this integration has the issue?
      placeholder: 1.1.4
      description: >
        Can be found in the Configuration panel -> Info.

  - type: input
    id: ha_version
    validations:
      required: true
    attributes:
      label: What version of Home Assistant Core has the issue?
      placeholder: core-2021.12.3
      description: >
        Can be found in the Configuration panel -> Info.

  - type: markdown
    attributes:
      value: |
        ## Details

  - type: textarea
    id: logs
    attributes:
      label: Home Assistant log
      description: Paste your full log here, [how to enable logs](../blob/main/README.md#collect-logs).
      render: shell

  - type: textarea
    id: diagnostics
    attributes:
      label: Diagnostics
      description: Paste your diagnostics content here, [how to get diagnostics](https://www.home-assistant.io/integrations/diagnostics/).
      render: json

  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: If you have any additional information for us, use the field below. Please note, you can attach screenshots or screen recordings here, by dragging and dropping files in the field below.

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
