ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

history:

http:
  trusted_proxies:
    - 127.0.0.1
    - ::1
  use_x_forwarded_for: true

logbook:

logger:
  default: warn
  logs:
    custom_components.knmi: debug
