#!/usr/bin/env bash

set -e

# Create a working directory for Home Assistant
sudo mkdir -p /hass
sudo chown vscode:vscode /hass

# Copy config and custom_components
rm -f /hass/configuration.yaml
cp .devcontainer/configuration.yaml /hass

rm -rf /hass/custom_components
cp -r custom_components/ /hass

# Start Home Assistant
hass -c /hass --debug
