#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

python3 -m pip install --upgrade --force-reinstall --requirement requirements.txt

if python -c "import pytest_homeassistant_custom_component" &> /dev/null; then
    # User also has test requirements, update those as well.
    python3 -m pip install --upgrade --force-reinstall --requirement requirements_test.txt
fi
