name: Release Drafter

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  update_release_draft:
    name: Update release draft
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v6

      - name: Setup app
        id: app
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.PR2D2_APP_ID }}
          private-key: ${{ secrets.PR2D2_APP_PRIVATE_KEY }}

      - name: Run release drafter
        uses: release-drafter/release-drafter@v7
        with:
          config-name: release-drafter.yaml
          token: ${{ steps.app.outputs.token }}
